### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by jimmykamau** [kelonye/python-pesapal#4]
The package doesn't work with python 3. I've created a fork for it at jimmykamau/python-pesapal

**Comment by kelonye** [comment]
Awesome :smirk: .. not sure when I'll move to py3.

**Comment by kelonye** [comment]
Probably try https://docs.python.org/3/howto/pyporting.html

**Comment by jimmykamau** [comment]
I've ported it. Uploaded it to pip as python3_pesapal
